BTH7_1621050274_PhamTaiSang/BTH7_1621050274_PhamTaiSang/Controllers/TrangChuController.cs
using BTH7_1621050274_PhamTaiSang.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTH7_1621050274_PhamTaiSang.Controllers
{
    public class TrangChuController : Controller
    {
        // GET: TrangChu
        Model db = new Model();

        public object Home { get; private set; }

        public ActionResult Index()
        {

            List<tbl_sinhvien> sinhvien = (from sv in db.tbl_sinhvien select sv).ToList();
            List<tbl_giangvien> giangvien = (from gv in db.tbl_giangvien select gv).ToList();
            List<tbl_doan> doan = (from da in db.tbl_doan select da).ToList();
            List<tbl_chuyennganh> nganh = (from p in db.tbl_chuyennganh select p).ToList();
            int demcn = (from p in db.tbl_chuyennganh select p).ToList().Count;
            int demsv = sinhvien.Count;
            int demgv = giangvien.Count;
            int demda = doan.Count;
            ViewBag.demcn = demcn;
            ViewBag.demsv = demsv;
            ViewBag.demgv = demgv;
            ViewBag.demda = demda;
            ViewBag.nganh = nganh;
            ViewBag.doan = doan;
            return View();           
        }
        public ActionResult getDanhsach(int id)
        {
            var sinhvien = ( from sv in db.tbl_sinhvien
                             join k in db.tbl_khoahoc on sv.Khoa equals k.Makh
                             join c in db.tbl_chuyennganh on sv.Chuyennganh equals c.Macn
                             where c.Macn == id
                             select sv).ToList();
            int dem = sinhvien.Count;
            ViewBag.dem = dem;
            ViewBag.sinhvien = sinhvien;
            return View();
        }

        public ActionResult test()
        {
            var khoa = db.tbl_khoahoc.ToList();
            return View(khoa);
        }
        public ActionResult ThemKhoaHoc()
        {
            
            return View();
        }
        [HttpPost]
        public ActionResult ThemKhoaHoc(tbl_khoahoc kh)
        {
            db.tbl_khoahoc.Add(kh);
            db.SaveChanges();
            return RedirectToAction("test");
        }
    }
}

BTH7_1621050274_PhamTaiSang/BTH7_1621050274_PhamTaiSang/Views/TrangChu/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@ViewBag.name1
<!-- Header -->
<header class="w3-container" style="padding-top:22px">
    <h5><i class="fa fa-dashboard"></i>TỔNG DỮ LIỆU HỆ THỐNG</h5>
</header>


<div class="w3-row-padding w3-margin-bottom">
    <div class="w3-quarter">
        <div class="w3-container w3-red w3-padding-16">
            <div class="w3-left"><i class="fa fa-user w3-xxxlarge"></i></div>
            <div class="w3-right">
                <h3>@Html.Raw(ViewBag.demsv)</h3>
            </div>
            <div class="w3-clear"></div>
            <h4>Hồ sơ sinh viên </h4>
        </div>
    </div>
    <div class="w3-quarter">
        <div class="w3-container w3-blue w3-padding-16">
            <div class="w3-left"><i class="fa fa-user w3-xxxlarge"></i></div>
            <div class="w3-right">
                <h3>@Html.Raw(ViewBag.demgv)</h3>
            </div>
            <div class="w3-clear"></div>
            <h4>Hồ sơ giảng viên </h4>
        </div>
    </div>
    <div class="w3-quarter">
        <div class="w3-container w3-green w3-padding-16">
            <div class="w3-left"><i class="fa fa-graduation-cap w3-xxxlarge"></i></div>
            <div class="w3-right">
                <h3>@Html.Raw(ViewBag.demda)</h3>
            </div>
            <div class="w3-clear"></div>
            <h4>Đồ án tốt nghiệp </h4>
        </div>
    </div>
    <div class="w3-quarter">
        <div class="w3-container w3-pink w3-padding-16">
            <div class="w3-left"><i class="fa fa-adjust w3-xxxlarge"></i></div>
            <div class="w3-right">
                <h3> @Html.Raw(ViewBag.demcn)</h3>
            </div>
            <div class="w3-clear"></div>
            <h4>Số chuyên ngành </h4>
        </div>
    </div>
</div>

<div>
    <header class="w3-container" style="padding-top:22px">
        <h5><i class="fa fa-bar-chart"></i>THỐNG KÊ SINH VIÊN TỪNG CHUYÊN NGÀNH</h5>
    </header>
    <table>
        <tr>
            <th>STT</th>
            <th>Chuyên ngành</th>
            <th>Số sinh viên </th>
            <th>Chi tiết</th>
        </tr>
        @foreach (var item in ViewBag.nganh)
        {
            var url = "/chuyen-nganh/" + item.Tencn + "-" + item.Macn;
            <tr>

                <td>@item.Macn</td>
                <td>@item.Tencn</td>
                <td>@item.tbl_sinhvien.Count</td>
                <td><a href="@url"><i class="fa fa-search"></i>Danh sách</a></td>


            </tr>
        }
    </table>



    <div id="show_DoAn">
        <table>
            <tr>
                <th>STT</th>
                <th>MaSV</th>
                <th>TenDoAn (Đồ án có điểm nhỏ hơn 7)</th>
                <th>Giáo viên HD</th>
                <th>Lĩnh vực</th>
                <th>Điểm</th>

            </tr>
            @{int dem7 = 0, dem8 = 0, dem9 = 0, dem10 = 0, stt = 0; }


            @foreach (var i in ViewBag.doan)
            {

                stt++;
                if (i.Diem < 7 || i.Diem == 7)
                {
                    dem7++;
                    <div class="showdiem7">

                        <tr>
                            <td>@stt</td>
                            <td>@i.Masv</td>
                            <td>@i.Tenda</td>
                            <td>@i.tbl_giangvien.Tengv</td>
                            <td>@i.tbl_linhvuc.Tenlv</td>
                            <td>@i.Diem</td>
                        </tr>

                    </div>


                }
                else if (i.Diem > 7 || i.Diem == 8)
                {
                    dem8++;

                }
                else if (i.Diem > 8 || i.Diem == 9)
                {
                    dem9++;
                }
                else
                {
                    dem10++;
                }

            }
        </table>
    </div>
    <div id="show_DoAn_8">
        <table>
            <tr>
                <th>STT</th>
                <th>MaSV</th>
                <th>TenDoAn (Đồ án có điểm từ 7đ đén 8đ )</th>
                <th>Giáo viên HD</th>
                <th>Lĩnh vực</th>
                <th>Điểm</th>

            </tr>
            @{ int st = 0;}
            @foreach (var i in ViewBag.doan)

            {
                if (i.Diem < 7 || i.Diem == 7)
                {

                }
                else if (i.Diem < 8 || i.Diem == 8)
                {
                    st++;
                    <tr>
                        <td>@st</td>
                        <td>@i.Masv</td>
                        <td>@i.Tenda</td>
                        <td>@i.tbl_giangvien.Tengv</td>
                        <td>@i.tbl_linhvuc.Tenlv</td>
                        <td>@i.Diem</td>

                    </tr>
                }
            }
        </table>
    </div>
    <div id="show_DoAn_9">
        <table>
            <tr>
                <th>STT</th>
                <th>MaSV</th>
                <th>TenDoAn (Đồ án có điểm từ 8đ đến 9đ )</th>
                <th>Giáo viên HD</th>
                <th>Lĩnh vực</th>
                <th>Điểm</th>

            </tr>
            @{ int st1 = 0;}
            @foreach (var i in ViewBag.doan)
            {
                if (i.Diem < 7 || i.Diem == 7)
                {

                }
                else if (i.Diem < 8 || i.Diem == 8)
                {

                }
                else if (i.Diem < 9 || i.Diem == 9)
                {
                    st1++;
                    <tr>
                        <td>@st1</td>
                        <td>@i.Masv</td>
                        <td>@i.Tenda</td>
                        <td>@i.tbl_giangvien.Tengv</td>
                        <td>@i.tbl_linhvuc.Tenlv</td>
                        <td>@i.Diem</td>
                    </tr>
                }
            }
        </table>
    </div>
    <div id="show_DoAn_10">
        <table>
            <tr>
                <th>STT</th>
                <th>MaSV</th>
                <th>TenDoAn (Đồ án có điểm từ 9đ đến 10đ )</th>
                <th>Giáo viên HD</th>
                <th>Lĩnh vực</th>
                <th>Điểm</th>

            </tr>
            @{ int st2 = 0;}
            @foreach (var i in ViewBag.doan)
            {
                if (i.Diem > 9 || i.Diem == 10)
                {
                    st2++;
                    <tr>
                        <td>@st2</td>
                        <td>@i.Masv</td>
                        <td>@i.Tenda</td>
                        <td>@i.tbl_giangvien.Tengv</td>
                        <td>@i.tbl_linhvuc.Tenlv</td>
                        <td>@i.Diem</td>
                    </tr>
                }
            }
        </table>
    </div>
    <header class="w3-container" style="padding-top:22px">
        <h5><i class="fa fa-bar-chart"></i>THỐNG KÊ DỒ ÁN THEO ĐIỂM</h5>
    </header>

    <div class="w3-grey" style="width:97%;margin:auto;">
        <div class="w3-container w3-left w3-padding w3-green" style="width:100%">Đồ án có điểm < = 7 ........ <span style="color:burlywood">@dem7  đồ án</span> <div style="cursor:pointer;color:black;" class="btn btnClick">Xem</div> </div>
    </div>

    <div class="w3-grey" style="width:97%;margin:auto;">
        <div class="w3-container w3-left w3-padding w3-red" style="width:100%">Đồ án có điểm từ 7.1 đến 8.0 ........<span style="color:burlywood">@st  đồ án</span> <div style="cursor:pointer;color:black;" class="btn btnClick1">Xem</div> </div>
    </div>

    <div class="w3-grey" style="width:97%;margin:auto;">
        <div class="w3-container w3-left w3-padding w3-blue" style="width:100%">Đồ án có điểm từ 8.1 đến 9.0 ........ <span style="color:burlywood">@st1 đồ án</span><div style="cursor:pointer;color:black;" class="btn btnClick2">Xem</div> </div>
    </div>

    <div class="w3-grey" style="width:97%;margin:auto;">
        <div class="w3-container w3-left w3-padding w3-blue-gray" style="width:100%">Đồ án có điểm từ 9.0 đến 10 ........ <span style="color:burlywood">@st2  đồ án</span> <div style="cursor:pointer;color:black;" class="btn btnClick3">Xem</div> </div>
    </div>

</div>

BTH7_1621050274_PhamTaiSang/BTH7_1621050274_PhamTaiSang/Views/TrangChu/ThemKhoaHoc.cshtml
@model BTH7_1621050274_PhamTaiSang.Models.tbl_khoahoc

@{
    ViewBag.Title = "ThemKhoaHoc";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ThemKhoaHoc</h2>

@using (Html.BeginForm("ThemKhoaHoc","TrangChu",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tbl_khoahoc</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Makh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Makh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Makh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tenkhoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Tenkhoa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tenkhoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thoigian, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Thoigian, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Thoigian, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ghichu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Ghichu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ghichu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BTH7_1621050274_PhamTaiSang/BTH7_1621050274_PhamTaiSang/Views/TrangChu/getDanhsach.cshtml
@{
    ViewBag.Title = "getDanhsach";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h5 class="pt-3 pl-2">DANH SÁCH SINH VIÊN THEO CHUYÊN NGÀNH</h5>
<p class="text-lg-right pr-2" style="color:darkgoldenrod; font-size:12px; font-weight:bold;">Tổng số bản ghi : @ViewBag.dem </pclass="pt-3>
<table>
    <tr>
        <th>STT</th>
        <th>Mã sinh viên</th>
        <th>Tên SV</th>
        <th>Ngày sinh</th>
        <th>Giới tính</th>
        <th>Khoa</th>
        <th>Chuyên ngành</th>
        <th>Email</th>
        <th>Điện thoại</th>
        <th>Địa chỉ</th>
    </tr>
    @{ 
        int i=0;
    }
    @foreach (var item in ViewBag.sinhvien)
    {

    <tr>
        <td>@{Write(i++);}</td>
        <td>@item.Masv</td>
        <td>@item.Tensv</td>
        <td>@item.Namsinh</td>
        <td>
           @if (@item.Gioitinh == true)
           {
               Write("Nữ");
           }
           else
           {
               Write("Nam");
           }

        </td>
        <td>@item.tbl_khoahoc.Tenkhoa</td>
        <td>@item.tbl_chuyennganh.Tencn</td>
        <td>@item.Email</td>
        <td>@item.Dienthoai</td>
        <td>@item.Diachi</td>
    </tr>
    }

</table>

BTH7_1621050274_PhamTaiSang/BTH7_1621050274_PhamTaiSang/Views/TrangChu/test.cshtml
@using BTH7_1621050274_PhamTaiSang.Models;
@Model List<tbl_khoahoc>
    @{
        ViewBag.Title = "test";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <h2>Khoa học</h2>
    <a href="@Url.Action("ThemKhoaHoc","TrangChu")">Them</a>
    <table>


        <tr>
            <th>ID</th>
            <th>Tên khoa</th>
            <th>Thời gian</th>
            <th>Ghi chú</th>
            <th>Số sinh viên</th>
        </tr>

        @foreach (var item in Model)
        {
        <tr>
            <td>@item.Makh;</td>
            <td>@item.Tenkhoa;</td>
            <td>@item.Thoigian;</td>
            <td>@item.Ghichu;</td>
            <td>@item.tbl_sinhvien.Count</td>
        </tr>
         }
    </table>