BTH7_1621050274_PhamTaiSang/BTH7_1621050274_PhamTaiSang/Controllers/SinhVienController.cs
using BTH7_1621050274_PhamTaiSang.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTH7_1621050274_PhamTaiSang.Controllers
{
    
    public class SinhVienController : Controller
    {
        // GET: SinhVien
        private Model db = new Model();
        public ActionResult Index()
        {
            var sinhvien = (from sv in db.tbl_sinhvien select sv).ToList();

            ViewBag.sinhvien = sinhvien;
            return View();
        }
        public ActionResult chitiet(string id)
        {
            //ViewBag.id = id;
            var sinhvien = (from sv in db.tbl_sinhvien  where sv.Masv == id select sv).ToList();
            ViewBag.sinhvien = sinhvien;
            return View();
        }
        public ActionResult sua(string id)
        {
            //ViewBag.id = id;
            var sinhvien = (from sv in db.tbl_sinhvien where sv.Masv == id select sv).ToList();
            ViewBag.sinhvien = sinhvien;
            return View();
        }
        [HttpGet]
        public ActionResult xoa(string id)
        {
            tbl_sinhvien sv = db.tbl_sinhvien.Find(id);
            db.tbl_sinhvien.Remove(sv);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult TimKiem(string searchString)
        {
            //ViewBag.timkiem = searchString;
            var links = from l in db.tbl_sinhvien // lấy toàn bộ liên kết
                        select l;

            if (!String.IsNullOrEmpty(searchString)) // kiểm tra chuỗi tìm kiếm có rỗng/null hay không
            {
                links = links.Where(s => s.Tensv.Contains(searchString)); //lọc theo chuỗi tìm kiếm
            }
         
            ViewBag.show = links;
            return View();
        }
    }
}

BTH7_1621050274_PhamTaiSang/BTH7_1621050274_PhamTaiSang/Views/SinhVien/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h5 class="pt-3 pl-2">DANH SÁCH SINH VIÊN</h5>
@{ int dem = 0; }
@foreach (var item in ViewBag.sinhvien)
{
    dem++;
}
<h3><a href="#">Thêm sinh viên </a></h3>
<!-- 1. Đoạn cần thêm -->

@using (Html.BeginForm("TimKiem", "SinhVien", FormMethod.Get))

{

<p>

    Title: @Html.TextBox("SearchString") <input type="submit" value="Tìm kiếm" />
</p>

}

<!-- Kết thúc -->
<p class="text-lg-right pr-2" style="color:darkgoldenrod; font-size:12px; font-weight:bold;">
    Tổng số bản ghi : @{ Write(dem); } </pclass="pt-3>
    <table>
        <tr>
            <th>STT</th>
            <th>Mã sinh viên</th>
            <th>Tên SV</th>
            <th>Ngày sinh</th>
            <th>Giới tính</th>
            <th>Chức năng</th>
            <th></th>
            <th></th>
        </tr>
        @{
            int i = 0;
        }
        @foreach (var item in ViewBag.sinhvien)
        {
            var url = "/sinh-vien/" + item.Tensv + "-" + item.Masv;
            var urlEdit = "/sua-sinh-vien/" + item.Tensv + "-" + item.Masv;
            var urlDel = "/xoa-sinh-vien/" + item.Tensv + "-" + item.Masv;
            <tr>
                <td>@{Write(i++);}</td>
                <td>@item.Masv</td>
                <td>@item.Tensv</td>
                <td>@item.Namsinh</td>
                <td>
                    @if (@item.Gioitinh == true)
                    {
                        Write("Nữ");
                    }
                    else
                    {
                        Write("Nam");
                    }

                </td>

                <td><a href="@url" style="color:red">View</a></td>
                <td><a href="@urlEdit" style="color:red">Edit</a></td>
                <td><a href="@urlDel" style="color:red">Delete</a></td>
            </tr>
        }

    </table>

BTH7_1621050274_PhamTaiSang/BTH7_1621050274_PhamTaiSang/Views/SinhVien/TimKiem.cshtml
@{
    ViewBag.Title = "TimKiem";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<table>
    <tr>

        <th>Mã sinh viên</th>
        <th>Tên SV</th>
        <th>Ngày sinh</th>
        <th>Giới tính</th>

    </tr>
    
    @foreach (var item in ViewBag.show)
    {
    
        <tr>
            <td>@item.Masv</td>
            <td>@item.Tensv</td>
            <td>@item.Namsinh</td>
            <td>
                @if (@item.Gioitinh == true)
                {
                    Write("Nữ");
                }
                else
                {
                    Write("Nam");
                }

            </td>
        </tr>
    }
       
</table>

BTH7_1621050274_PhamTaiSang/BTH7_1621050274_PhamTaiSang/Views/SinhVien/chitiet.cshtml
@{
    ViewBag.Title = "chitiet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>THÔNG TIN CHI TIẾT SINH VIÊN</h2>

@foreach(var i in ViewBag.sinhvien)
{
<div class="chitietsv">
    <p>Mã sinh viên là : @i.Masv</p>
    <p>Tên sinh viên là :@i.Tensv</p>
    <p>Năm sinh : @i.Namsinh</p>
    <p>Giới tính : @i.Khoa</p>
    <p>Khoa : @i.tbl_khoahoc.Tenkhoa</p>
    <p>Chuyên ngành : @i.tbl_chuyennganh.Tencn</p>
    <p>Email : @i.Email</p>
    <p>Điện thoại :@i.Dienthoai</p>
    <p>Địa chỉ : @i.Diachi</p>
    <p>Ghi chú : @i.Ghichu</p>
</div>
}